# Generated by Django 5.2.9 on 2026-01-03 22:03

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostDetail",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "druh_type",
                    models.CharField(
                        choices=[("vydaje", "Výdaje"), ("prijmy", "Příjmy")],
                        max_length=20,
                    ),
                ),
                ("druh_value", models.CharField(max_length=50)),
                ("detail", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Druh nákladu",
                "verbose_name_plural": "Druhy nákladů",
                "db_table": "transactions_cost_detail",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[("SKOLY", "ŠKOLY"), ("FIRMY", "FIRMY")], max_length=20
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Produkt",
                "verbose_name_plural": "Produkty",
                "db_table": "transactions_product",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Projekt",
                "verbose_name_plural": "Projekty",
                "db_table": "transactions_project",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("error_details", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Batch",
                "verbose_name_plural": "Import Batches",
                "db_table": "transactions_import_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductSubgroup",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgroups",
                        to="transactions.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podskupina produktu",
                "verbose_name_plural": "Podskupiny produktů",
                "db_table": "transactions_product_subgroup",
                "ordering": ["product", "name"],
            },
        ),
        migrations.CreateModel(
            name="CategoryRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Rule Name")),
                ("description", models.TextField(blank=True)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("protiucet", "Protiúčet (Account Number)"),
                            ("merchant", "Merchant Name"),
                            ("keyword", "Keyword (Regex/Exact)"),
                        ],
                        max_length=20,
                        verbose_name="Match Type",
                    ),
                ),
                (
                    "match_mode",
                    models.CharField(
                        choices=[
                            ("exact", "Exact Match"),
                            ("contains", "Contains"),
                            ("regex", "Regular Expression"),
                        ],
                        default="exact",
                        max_length=20,
                        verbose_name="Match Mode",
                    ),
                ),
                (
                    "match_value",
                    models.CharField(
                        help_text="Account number, merchant name, or keyword/regex pattern",
                        max_length=500,
                        verbose_name="Match Value",
                    ),
                ),
                (
                    "case_sensitive",
                    models.BooleanField(default=False, verbose_name="Case Sensitive"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=100, verbose_name="Priority"),
                ),
                (
                    "set_prijem_vydaj",
                    models.CharField(
                        blank=True,
                        choices=[("P", "Příjem"), ("V", "Výdaj")],
                        max_length=1,
                        verbose_name="Set P/V",
                    ),
                ),
                (
                    "set_vlastni_nevlastni",
                    models.CharField(
                        blank=True,
                        choices=[("V", "Vlastní"), ("N", "Nevlastní"), ("-", "—")],
                        max_length=1,
                        verbose_name="Set V/N",
                    ),
                ),
                (
                    "set_dane",
                    models.BooleanField(blank=True, null=True, verbose_name="Set Daně"),
                ),
                (
                    "set_druh",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Set Druh"
                    ),
                ),
                (
                    "set_detail",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Set Detail"
                    ),
                ),
                (
                    "set_kmen",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MH", "MH"),
                            ("SK", "ŠK"),
                            ("XP", "XP"),
                            ("FR", "FR"),
                        ],
                        max_length=2,
                        verbose_name="Set KMEN",
                    ),
                ),
                (
                    "set_mh_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Set MH%",
                    ),
                ),
                (
                    "set_sk_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Set ŠK%",
                    ),
                ),
                (
                    "set_xp_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Set XP%",
                    ),
                ),
                (
                    "set_fr_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Set FR%",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "set_produkt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transactions.product",
                        verbose_name="Set Produkt",
                    ),
                ),
                (
                    "set_podskupina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transactions.productsubgroup",
                        verbose_name="Set Podskupina",
                    ),
                ),
                (
                    "set_projekt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transactions.project",
                        verbose_name="Set Projekt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pravidlo kategorizace",
                "verbose_name_plural": "Pravidla kategorizace",
                "db_table": "transactions_category_rule",
                "ordering": ["match_type", "priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["match_type", "is_active", "priority"],
                        name="transaction_match_t_dcbede_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        db_index=True, editable=False, verbose_name="Datum"
                    ),
                ),
                (
                    "ucet",
                    models.CharField(
                        editable=False, max_length=50, verbose_name="Účet"
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="Typ"
                    ),
                ),
                (
                    "poznamka_zprava",
                    models.TextField(
                        blank=True, editable=False, verbose_name="Poznámka/Zpráva"
                    ),
                ),
                (
                    "variabilni_symbol",
                    models.CharField(
                        blank=True, editable=False, max_length=20, verbose_name="VS"
                    ),
                ),
                (
                    "castka",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="Částka",
                    ),
                ),
                (
                    "datum_zauctovani",
                    models.DateField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Datum zaúčtování",
                    ),
                ),
                (
                    "cislo_protiuctu",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=50,
                        verbose_name="Číslo protiúčtu",
                    ),
                ),
                (
                    "nazev_protiuctu",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=200,
                        verbose_name="Název protiúčtu",
                    ),
                ),
                (
                    "typ_transakce",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        verbose_name="Typ transakce",
                    ),
                ),
                (
                    "konstantni_symbol",
                    models.CharField(
                        blank=True, editable=False, max_length=10, verbose_name="KS"
                    ),
                ),
                (
                    "specificky_symbol",
                    models.CharField(
                        blank=True, editable=False, max_length=20, verbose_name="SS"
                    ),
                ),
                (
                    "puvodni_castka",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        null=True,
                        verbose_name="Původní částka",
                    ),
                ),
                (
                    "puvodni_mena",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        verbose_name="Původní měna",
                    ),
                ),
                (
                    "poplatky",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        null=True,
                        verbose_name="Poplatky",
                    ),
                ),
                (
                    "id_transakce",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=100,
                        verbose_name="Id transakce",
                    ),
                ),
                (
                    "vlastni_poznamka",
                    models.TextField(
                        blank=True, editable=False, verbose_name="Vlastní poznámka"
                    ),
                ),
                (
                    "nazev_merchanta",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=200,
                        verbose_name="Název merchanta",
                    ),
                ),
                (
                    "mesto",
                    models.CharField(
                        blank=True, editable=False, max_length=100, verbose_name="Město"
                    ),
                ),
                (
                    "mena",
                    models.CharField(
                        default="CZK",
                        editable=False,
                        max_length=10,
                        verbose_name="Měna",
                    ),
                ),
                (
                    "banka_protiuctu",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        verbose_name="Banka protiúčtu",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        verbose_name="Reference",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("importovano", "Importováno"),
                            ("zpracovano", "Zpracováno"),
                            ("schvaleno", "Schváleno"),
                            ("upraveno", "Upraveno"),
                            ("chyba", "Chyba"),
                        ],
                        db_index=True,
                        default="importovano",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "prijem_vydaj",
                    models.CharField(
                        blank=True,
                        choices=[("P", "Příjem"), ("V", "Výdaj")],
                        max_length=1,
                        verbose_name="P/V",
                    ),
                ),
                (
                    "vlastni_nevlastni",
                    models.CharField(
                        choices=[("V", "Vlastní"), ("N", "Nevlastní"), ("-", "—")],
                        default="-",
                        max_length=1,
                        verbose_name="V/N",
                    ),
                ),
                ("dane", models.BooleanField(default=False, verbose_name="Daně")),
                (
                    "druh",
                    models.CharField(blank=True, max_length=50, verbose_name="Druh"),
                ),
                (
                    "detail",
                    models.CharField(blank=True, max_length=200, verbose_name="Detail"),
                ),
                (
                    "kmen",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MH", "MH"),
                            ("SK", "ŠK"),
                            ("XP", "XP"),
                            ("FR", "FR"),
                        ],
                        max_length=2,
                        verbose_name="KMEN",
                    ),
                ),
                (
                    "mh_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="MH%",
                    ),
                ),
                (
                    "sk_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="ŠK%",
                    ),
                ),
                (
                    "xp_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="XP%",
                    ),
                ),
                (
                    "fr_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="FR%",
                    ),
                ),
                (
                    "import_batch_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Import Batch ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "podskupina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="transactions.productsubgroup",
                        verbose_name="Podskupina",
                    ),
                ),
                (
                    "produkt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="transactions.product",
                        verbose_name="Produkt",
                    ),
                ),
                (
                    "projekt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="transactions.project",
                        verbose_name="Projekt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transakce",
                "verbose_name_plural": "Transakce",
                "db_table": "transactions_transaction",
                "ordering": ["-datum", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["datum", "status"], name="transaction_datum_01a1b6_idx"
                    ),
                    models.Index(
                        fields=["kmen", "datum"], name="transaction_kmen_fd658e_idx"
                    ),
                    models.Index(
                        fields=["projekt", "datum"],
                        name="transaction_projekt_1ac1f1_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("fr_pct", 0),
                                ("mh_pct", 0),
                                ("sk_pct", 0),
                                ("xp_pct", 0),
                            ),
                            models.Q(
                                ("fr_pct__gte", 0),
                                ("mh_pct__gte", 0),
                                ("sk_pct__gte", 0),
                                ("xp_pct__gte", 0),
                            ),
                            _connector="OR",
                        ),
                        name="kmen_pct_sum_equals_100_or_zero",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("id_transakce", ""), _negated=True),
                        fields=("id_transakce",),
                        name="unique_bank_transaction_id",
                    ),
                ],
            },
        ),
    ]
