# Generated by Django 5.2.8 on 2026-02-04 01:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDokladInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cislo_dokladu', models.CharField(db_index=True, max_length=50, unique=True)),
                ('popis', models.TextField(blank=True)),
                ('cislo_objednavky', models.CharField(blank=True, max_length=50)),
                ('rada', models.CharField(blank=True, max_length=50)),
                ('nazev_jmeno', models.CharField(blank=True, max_length=500)),
                ('ic', models.CharField(blank=True, max_length=20)),
                ('dic_ic_dph', models.CharField(blank=True, max_length=30)),
                ('dic_sk', models.CharField(blank=True, max_length=30)),
                ('vystaveno', models.DateField(blank=True, null=True, verbose_name='Vystaveno')),
                ('splatnost', models.DateField(blank=True, null=True, verbose_name='Splatnost')),
                ('duzp', models.DateField(blank=True, null=True, verbose_name='DUZP')),
                ('datum_platby', models.DateField(blank=True, null=True, verbose_name='Datum platby')),
                ('celkem_s_dph', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('celkem_bez_dph', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dph', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mena', models.CharField(blank=True, max_length=10)),
                ('stav_uhrady', models.CharField(blank=True, max_length=50)),
                ('uhrazena_castka', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('variabilni_symbol', models.CharField(blank=True, db_index=True, max_length=20)),
                ('exportovano', models.BooleanField(default=False)),
                ('odeslano_odberateli', models.CharField(blank=True, max_length=50)),
                ('odeslano_uctovnemu', models.BooleanField(default=False)),
                ('import_batch_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Import Batch ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idoklad_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'iDoklad Invoice',
                'verbose_name_plural': 'iDoklad Invoices',
                'db_table': 'transactions_idoklad_invoice',
                'ordering': ['-vystaveno'],
                'indexes': [models.Index(fields=['variabilni_symbol'], name='transaction_variabi_9c24b0_idx'), models.Index(fields=['vystaveno'], name='transaction_vystave_7e305e_idx')],
            },
        ),
    ]
