# Generated by Django 5.2.8 on 2026-03-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_create_transaction_audit_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', 'category', 'name'], 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='productsubgroup',
            options={'ordering': ['product', 'sort_order', 'name'], 'verbose_name': 'Podskupina produktu', 'verbose_name_plural': 'Podskupiny produktů'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Projekt', 'verbose_name_plural': 'Projekty'},
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Pořadí zobrazení (vzestupně)'),
        ),
        migrations.AddField(
            model_name='productsubgroup',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Pořadí zobrazení (vzestupně)'),
        ),
        migrations.AddField(
            model_name='project',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Pořadí zobrazení (vzestupně)'),
        ),
    ]
