# Generated by Django 5.2.8 on 2026-03-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_set_initial_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vyplaceno',
            field=models.BooleanField(default=False, help_text='Relevantní pouze pro hotovost/karta', verbose_name='Vyplaceno'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='zdroj_transakce',
            field=models.CharField(choices=[('ucet', 'Účet'), ('hotovost', 'Hotovost'), ('karta', 'Karta')], default='ucet', max_length=20, verbose_name='Zdroj transakce'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mena',
            field=models.CharField(choices=[('CZK', 'CZK'), ('EUR', 'EUR')], default='CZK', editable=False, max_length=10, verbose_name='Měna'),
        ),
    ]
