# Generated by Django 5.2.8 on 2026-03-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_add_zdroj_transakce_vyplaceno_mena_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrule',
            name='match_mode',
            field=models.CharField(choices=[('exact', 'Přesná shoda'), ('contains', 'Obsahuje'), ('starts_with', 'Začíná na')], default='exact', max_length=20, verbose_name='Match Mode'),
        ),
        migrations.AlterField(
            model_name='categoryrule',
            name='match_type',
            field=models.CharField(choices=[('protiucet', 'Protiúčet (Číslo účtu)'), ('merchant', 'Název obchodníka'), ('keyword', 'Klíčové slovo (zpráva/poznámka)'), ('typ', 'Typ transakce'), ('vs', 'Variabilní symbol'), ('mesto', 'Město')], max_length=20, verbose_name='Match Type'),
        ),
    ]
