# Generated by Django 5.2.8 on 2026-03-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_update_match_type_mode_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='zodpovedna_osoba',
            field=models.CharField(blank=True, max_length=200, verbose_name='Zodpovědná osoba'),
        ),
    ]
