# Generated by Django 5.2.8 on 2026-03-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_add_zodpovedna_osoba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrule',
            name='match_value',
            field=models.CharField(help_text='Account number, merchant name, keyword, or other match value', max_length=500, verbose_name='Match Value'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('importovano', 'Importováno'), ('zpracovano', 'Zpracováno'), ('schvaleno', 'Schváleno'), ('upraveno', 'Upraveno'), ('ceka_na_schvaleni', 'Čeká na schválení'), ('chyba', 'Chyba')], db_index=True, default='importovano', max_length=20, verbose_name='Status'),
        ),
    ]
