# Generated by Django 5.2.8 on 2026-03-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_add_ceka_na_schvaleni_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costdetail',
            options={'ordering': ['druh_type', 'sort_order', 'druh_value', 'detail'], 'verbose_name': 'Druh nákladu', 'verbose_name_plural': 'Druhy nákladů'},
        ),
        migrations.AddField(
            model_name='costdetail',
            name='poznamka',
            field=models.TextField(blank=True, default='', verbose_name='Poznámka'),
        ),
        migrations.AddField(
            model_name='costdetail',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costdetail',
            name='druh_value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='costdetail',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
